import type { BlogPost, Formation, Podcast, Video, Testimonial, FAQ, Announcement } from '../types';

export const blogPosts: BlogPost[] = [
  {
    id: '1',
    title: 'Comment doubler votre trafic organique en 6 mois',
    slug: 'doubler-trafic-organique-6-mois',
    excerpt: 'Decouvrez les strategies SEO qui m\'ont permis d\'atteindre une croissance de 1790% en un an. Des techniques concretes et actionnables.',
    content: `Le SEO n'est pas une science obscure. C'est une discipline qui demande de la rigueur, de la patience et une bonne comprehension de votre audience.\n\nDans cet article, je partage les strategies exactes qui m'ont permis d'atteindre une croissance spectaculaire du trafic organique.\n\n## 1. L'audit technique\n\nAvant toute chose, assurez-vous que votre site est techniquement sain. Vitesse de chargement, structure des URLs, balisage semantique...\n\n## 2. La strategie de contenu\n\nCreez du contenu qui repond aux vraies questions de votre audience. Utilisez les outils de recherche de mots-cles pour identifier les opportunites.\n\n## 3. Le maillage interne\n\nChaque page de votre site doit etre liee aux autres de maniere logique et strategique.\n\n## 4. La promotion\n\nLe meilleur contenu du monde ne sert a rien si personne ne le voit. Partagez, collaborez, creez des liens.`,
    coverImage: 'https://images.pexels.com/photos/590016/pexels-photo-590016.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'SEO',
    tags: ['SEO', 'Trafic', 'Growth'],
    author: 'Max-Morrys',
    publishedAt: '2026-02-20',
    readTime: 8,
    featured: true,
    status: 'published',
  },
  {
    id: '2',
    title: 'Les 5 piliers d\'une strategie digitale reussie',
    slug: 'piliers-strategie-digitale',
    excerpt: 'Une strategie digitale efficace repose sur des fondamentaux solides. Voici les 5 piliers indispensables pour reussir.',
    content: `La transformation digitale n'est plus une option mais une necessite pour toute entreprise qui souhaite rester competitive.\n\n## 1. La presence en ligne\n\nVotre site web est votre vitrine. Il doit etre professionnel, rapide et optimise pour la conversion.\n\n## 2. Le contenu\n\nContent is king. Creez du contenu de valeur qui positionne votre expertise.\n\n## 3. Les reseaux sociaux\n\nChoisissez les plateformes ou se trouve votre audience et soyez regulier.\n\n## 4. L'email marketing\n\nL'email reste le canal avec le meilleur ROI. Construisez votre liste.\n\n## 5. L'analyse des donnees\n\nMesurez tout. Optimisez en continu.`,
    coverImage: 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Strategie',
    tags: ['Strategie', 'Digital', 'Marketing'],
    author: 'Max-Morrys',
    publishedAt: '2026-02-15',
    readTime: 6,
    featured: false,
    status: 'published',
  },
  {
    id: '3',
    title: 'Intelligence Artificielle : guide pratique pour les entrepreneurs',
    slug: 'ia-guide-pratique-entrepreneurs',
    excerpt: 'L\'IA revolutionne le business. Voici comment l\'integrer concretement dans votre activite sans expertise technique.',
    content: `L'Intelligence Artificielle n'est plus reservee aux geants de la tech. Aujourd'hui, tout entrepreneur peut en tirer parti.\n\n## Comprendre l'IA\n\nL'IA, c'est simplement des algorithmes qui apprennent des donnees pour automatiser des taches ou prendre des decisions.\n\n## Applications concretes\n\n- Chatbots pour le service client\n- Analyse predictive pour les ventes\n- Creation de contenu assistee\n- Automatisation du marketing\n\n## Par ou commencer ?\n\nCommencez petit. Identifiez une tache repetitive dans votre business et trouvez un outil IA pour l'automatiser.`,
    coverImage: 'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'IA',
    tags: ['IA', 'Entrepreneuriat', 'Innovation'],
    author: 'Max-Morrys',
    publishedAt: '2026-02-10',
    readTime: 5,
    featured: true,
    status: 'published',
  },
  {
    id: '4',
    title: 'Creer une marque personnelle forte sur LinkedIn',
    slug: 'marque-personnelle-linkedin',
    excerpt: 'LinkedIn est devenu incontournable pour construire votre personal brand. Voici la methode complete.',
    content: `LinkedIn compte plus de 900 millions de membres. C'est LA plateforme pour construire votre marque professionnelle.\n\n## Optimisez votre profil\n\nVotre profil est votre landing page. Photo professionnelle, headline percutante, resume engageant.\n\n## Publiez regulierement\n\nLa regularite est la cle. 3 a 5 posts par semaine minimum.\n\n## Engagez avec votre communaute\n\nCommentez, partagez, repondez. L'algorithme recompense l'engagement.`,
    coverImage: 'https://images.pexels.com/photos/3182812/pexels-photo-3182812.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Personal Branding',
    tags: ['LinkedIn', 'Personal Branding', 'Reseaux Sociaux'],
    author: 'Max-Morrys',
    publishedAt: '2026-02-05',
    readTime: 7,
    featured: false,
    status: 'published',
  },
  {
    id: '5',
    title: 'Le marketing de contenu en Afrique : opportunites et defis',
    slug: 'marketing-contenu-afrique',
    excerpt: 'Le marche africain offre des opportunites uniques pour le content marketing. Analyse et strategies adaptees.',
    content: `L'Afrique est le continent de l'avenir pour le digital. Avec une population jeune et de plus en plus connectee, les opportunites sont immenses.\n\n## Le contexte africain\n\nMobile-first, WhatsApp-centric, avec des specificites culturelles fortes.\n\n## Les opportunites\n\n- Faible concurrence sur beaucoup de niches\n- Audience avide de contenu de qualite en francais\n- Croissance exponentielle de l'acces internet\n\n## Les defis\n\n- Connectivite variable\n- Moyens de paiement\n- Confiance digitale`,
    coverImage: 'https://images.pexels.com/photos/3184339/pexels-photo-3184339.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Marketing',
    tags: ['Afrique', 'Content Marketing', 'Digital'],
    author: 'Max-Morrys',
    publishedAt: '2026-01-28',
    readTime: 9,
    featured: false,
    status: 'published',
  },
  {
    id: '6',
    title: 'Comment monetiser vos competences avec des formations en ligne',
    slug: 'monetiser-competences-formations-en-ligne',
    excerpt: 'Transformez votre expertise en revenus recurrents grace aux formations en ligne. Guide etape par etape.',
    content: `La creation de formations en ligne est l'un des meilleurs moyens de monetiser son expertise tout en aidant les autres.\n\n## Identifiez votre expertise\n\nQu'est-ce que vous savez faire mieux que la plupart des gens ?\n\n## Validez la demande\n\nAvant de creer, assurez-vous qu'il y a un marche.\n\n## Structurez votre cours\n\nModules, lecons, exercices pratiques. La structure est cle.\n\n## Lancez et iterez\n\nLancez une premiere version, recoltez les retours, ameliorez.`,
    coverImage: 'https://images.pexels.com/photos/4144923/pexels-photo-4144923.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Formation',
    tags: ['Formation', 'Monetisation', 'E-learning'],
    author: 'Max-Morrys',
    publishedAt: '2026-01-20',
    readTime: 6,
    featured: false,
    status: 'published',
  },
];

export const formations: Formation[] = [
  {
    id: '1',
    title: 'Maitrisez le SEO de A a Z',
    slug: 'maitrisez-seo-a-z',
    description: 'Apprenez toutes les techniques SEO pour dominer les resultats de recherche.',
    longDescription: 'Cette formation complete vous guidera a travers toutes les facettes du SEO moderne. De l\'audit technique a la strategie de contenu, en passant par le netlinking et l\'analyse des donnees. Vous sortirez de cette formation avec toutes les competences necessaires pour positionner n\'importe quel site en premiere page de Google.',
    coverImage: 'https://images.pexels.com/photos/270637/pexels-photo-270637.jpeg?auto=compress&cs=tinysrgb&w=800',
    level: 'intermediaire',
    price: 150000,
    promoPrice: 99000,
    duration: '24h de contenu',
    category: 'SEO',
    tags: ['SEO', 'Google', 'Trafic'],
    students: 342,
    rating: 4.8,
    status: 'published',
    featured: true,
    certificateEnabled: true,
    modules: [
      {
        id: 'm1',
        title: 'Les fondamentaux du SEO',
        order: 1,
        lessons: [
          { id: 'l1', title: 'Introduction au SEO', type: 'video', duration: '15min', content: 'Comprendre les bases du referencement naturel.', videoUrl: '', order: 1, isFree: true },
          { id: 'l2', title: 'Comment fonctionne Google', type: 'video', duration: '22min', content: 'Le fonctionnement de l\'algorithme Google.', videoUrl: '', order: 2, isFree: true },
          { id: 'l3', title: 'Quiz - Fondamentaux', type: 'quiz', duration: '10min', content: '', order: 3, isFree: false },
        ],
      },
      {
        id: 'm2',
        title: 'Audit technique',
        order: 2,
        lessons: [
          { id: 'l4', title: 'Analyser la structure de votre site', type: 'video', duration: '30min', content: '', videoUrl: '', order: 1, isFree: false },
          { id: 'l5', title: 'Optimiser la vitesse de chargement', type: 'video', duration: '25min', content: '', videoUrl: '', order: 2, isFree: false },
          { id: 'l6', title: 'Le mobile-first indexing', type: 'text', duration: '15min', content: '', order: 3, isFree: false },
        ],
      },
      {
        id: 'm3',
        title: 'Strategie de contenu SEO',
        order: 3,
        lessons: [
          { id: 'l7', title: 'Recherche de mots-cles', type: 'video', duration: '35min', content: '', videoUrl: '', order: 1, isFree: false },
          { id: 'l8', title: 'Rediger pour le SEO', type: 'video', duration: '28min', content: '', videoUrl: '', order: 2, isFree: false },
          { id: 'l9', title: 'Mission pratique', type: 'mission', duration: '1h', content: '', order: 3, isFree: false },
        ],
      },
    ],
  },
  {
    id: '2',
    title: 'Marketing Digital Complet',
    slug: 'marketing-digital-complet',
    description: 'La formation la plus complete pour maitriser tous les leviers du marketing digital.',
    longDescription: 'Du social media au growth hacking, en passant par l\'email marketing et la publicite en ligne. Cette formation couvre l\'ensemble des competences necessaires pour devenir un expert du marketing digital. Avec des cas pratiques bases sur des entreprises africaines et internationales.',
    coverImage: 'https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg?auto=compress&cs=tinysrgb&w=800',
    level: 'debutant',
    price: 200000,
    promoPrice: 149000,
    duration: '36h de contenu',
    category: 'Marketing',
    tags: ['Marketing', 'Digital', 'Social Media'],
    students: 521,
    rating: 4.9,
    status: 'published',
    featured: true,
    certificateEnabled: true,
    modules: [
      {
        id: 'm4',
        title: 'Introduction au marketing digital',
        order: 1,
        lessons: [
          { id: 'l10', title: 'Le paysage digital en 2026', type: 'video', duration: '20min', content: '', videoUrl: '', order: 1, isFree: true },
          { id: 'l11', title: 'Definir sa strategie', type: 'video', duration: '25min', content: '', videoUrl: '', order: 2, isFree: true },
        ],
      },
      {
        id: 'm5',
        title: 'Social Media Marketing',
        order: 2,
        lessons: [
          { id: 'l12', title: 'Facebook & Instagram Ads', type: 'video', duration: '40min', content: '', videoUrl: '', order: 1, isFree: false },
          { id: 'l13', title: 'LinkedIn pour les pros', type: 'video', duration: '30min', content: '', videoUrl: '', order: 2, isFree: false },
        ],
      },
    ],
  },
  {
    id: '3',
    title: 'L\'IA pour les Entrepreneurs',
    slug: 'ia-pour-entrepreneurs',
    description: 'Integrez l\'intelligence artificielle dans votre business pour gagner en productivite.',
    longDescription: 'L\'IA n\'est plus un luxe. Cette formation vous montre comment l\'utiliser concretement pour automatiser vos taches, ameliorer votre marketing, optimiser vos ventes et gagner un avantage competitif. Pas besoin d\'etre technique.',
    coverImage: 'https://images.pexels.com/photos/8386434/pexels-photo-8386434.jpeg?auto=compress&cs=tinysrgb&w=800',
    level: 'debutant',
    price: 120000,
    duration: '18h de contenu',
    category: 'IA',
    tags: ['IA', 'ChatGPT', 'Productivite'],
    students: 189,
    rating: 4.7,
    status: 'published',
    featured: true,
    certificateEnabled: true,
    modules: [
      {
        id: 'm6',
        title: 'Comprendre l\'IA',
        order: 1,
        lessons: [
          { id: 'l14', title: 'Qu\'est-ce que l\'IA ?', type: 'video', duration: '18min', content: '', videoUrl: '', order: 1, isFree: true },
          { id: 'l15', title: 'Les outils IA essentiels', type: 'video', duration: '25min', content: '', videoUrl: '', order: 2, isFree: false },
        ],
      },
    ],
  },
  {
    id: '4',
    title: 'Personal Branding : Devenez une Reference',
    slug: 'personal-branding-reference',
    description: 'Construisez une marque personnelle forte qui attire clients et opportunites.',
    longDescription: 'Votre marque personnelle est votre actif le plus precieux. Cette formation vous apprend a la construire strategiquement, a communiquer votre valeur unique et a devenir la reference dans votre domaine.',
    coverImage: 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=800',
    level: 'intermediaire',
    price: 95000,
    duration: '12h de contenu',
    category: 'Personal Branding',
    tags: ['Personal Branding', 'Communication', 'Influence'],
    students: 278,
    rating: 4.9,
    status: 'published',
    featured: false,
    certificateEnabled: true,
    modules: [
      {
        id: 'm7',
        title: 'Les bases du personal branding',
        order: 1,
        lessons: [
          { id: 'l16', title: 'Definir votre positionnement', type: 'video', duration: '22min', content: '', videoUrl: '', order: 1, isFree: true },
          { id: 'l17', title: 'Creer votre univers visuel', type: 'video', duration: '20min', content: '', videoUrl: '', order: 2, isFree: false },
        ],
      },
    ],
  },
  {
    id: '5',
    title: 'Growth Hacking Avance',
    slug: 'growth-hacking-avance',
    description: 'Les techniques avancees de growth hacking pour accelerer votre croissance.',
    longDescription: 'Apprenez les techniques utilisees par les startups a forte croissance. Funnel AARRR, experimentation rapide, automatisation et scaling.',
    coverImage: 'https://images.pexels.com/photos/7688336/pexels-photo-7688336.jpeg?auto=compress&cs=tinysrgb&w=800',
    level: 'avance',
    price: 175000,
    duration: '20h de contenu',
    category: 'Growth',
    tags: ['Growth', 'Hacking', 'Startup'],
    students: 156,
    rating: 4.6,
    status: 'published',
    featured: false,
    certificateEnabled: true,
    modules: [
      {
        id: 'm8',
        title: 'Le framework AARRR',
        order: 1,
        lessons: [
          { id: 'l18', title: 'Acquisition', type: 'video', duration: '30min', content: '', videoUrl: '', order: 1, isFree: true },
          { id: 'l19', title: 'Activation & Retention', type: 'video', duration: '35min', content: '', videoUrl: '', order: 2, isFree: false },
        ],
      },
    ],
  },
];

export const podcasts: Podcast[] = [
  {
    id: '1',
    title: 'Le futur du marketing digital en Afrique',
    slug: 'futur-marketing-digital-afrique',
    description: 'Discussion sur les tendances du marketing digital en Afrique et les opportunites pour les entrepreneurs.',
    audioUrl: '',
    coverImage: 'https://images.pexels.com/photos/3756767/pexels-photo-3756767.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '45min',
    publishedAt: '2026-02-18',
    category: 'Marketing',
    status: 'published',
  },
  {
    id: '2',
    title: 'Comment j\'ai construit ma marque personnelle',
    slug: 'comment-construit-marque-personnelle',
    description: 'Mon parcours, mes erreurs et les lecons apprises en construisant la marque Max-Morrys.',
    audioUrl: '',
    coverImage: 'https://images.pexels.com/photos/4065876/pexels-photo-4065876.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '38min',
    publishedAt: '2026-02-10',
    category: 'Personal Branding',
    status: 'published',
  },
  {
    id: '3',
    title: 'L\'IA va-t-elle remplacer les marketeurs ?',
    slug: 'ia-remplacer-marketeurs',
    description: 'Debat sur l\'impact de l\'intelligence artificielle sur les metiers du marketing.',
    audioUrl: '',
    coverImage: 'https://images.pexels.com/photos/8386365/pexels-photo-8386365.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '52min',
    publishedAt: '2026-01-25',
    category: 'IA',
    status: 'published',
  },
];

export const videos: Video[] = [
  {
    id: '1',
    title: 'SEO en 2026 : les strategies qui marchent vraiment',
    slug: 'seo-2026-strategies',
    description: 'Les techniques SEO les plus efficaces pour 2026, testees et approuvees.',
    videoUrl: '',
    thumbnailUrl: 'https://images.pexels.com/photos/267350/pexels-photo-267350.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '18min',
    publishedAt: '2026-02-22',
    category: 'SEO',
    views: 12500,
    status: 'published',
  },
  {
    id: '2',
    title: 'Creer du contenu viral sur LinkedIn',
    slug: 'contenu-viral-linkedin',
    description: 'Ma methode pour creer des posts LinkedIn qui generent des milliers de vues.',
    videoUrl: '',
    thumbnailUrl: 'https://images.pexels.com/photos/5077047/pexels-photo-5077047.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '22min',
    publishedAt: '2026-02-14',
    category: 'Reseaux Sociaux',
    views: 8900,
    status: 'published',
  },
  {
    id: '3',
    title: 'ChatGPT : 10 prompts qui changent tout',
    slug: 'chatgpt-10-prompts',
    description: '10 techniques de prompting avancees pour tirer le maximum de ChatGPT.',
    videoUrl: '',
    thumbnailUrl: 'https://images.pexels.com/photos/8438922/pexels-photo-8438922.jpeg?auto=compress&cs=tinysrgb&w=800',
    duration: '15min',
    publishedAt: '2026-02-06',
    category: 'IA',
    views: 21300,
    status: 'published',
  },
];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Aminata Diallo',
    role: 'Fondatrice',
    company: 'DigiSenegal',
    content: 'Grace aux formations de Max-Morrys, j\'ai pu tripler le trafic de mon site en 4 mois. Les cours sont clairs, pratiques et directement applicables.',
    avatar: 'https://images.pexels.com/photos/3769021/pexels-photo-3769021.jpeg?auto=compress&cs=tinysrgb&w=200',
    rating: 5,
    featured: true,
  },
  {
    id: '2',
    name: 'Moussa Ndiaye',
    role: 'Directeur Marketing',
    company: 'TechDakar',
    content: 'La formation Marketing Digital Complet est un investissement que je recommande a 100%. Le ROI est impressionnant.',
    avatar: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=200',
    rating: 5,
    featured: true,
  },
  {
    id: '3',
    name: 'Fatou Sow',
    role: 'Entrepreneure',
    company: 'FashionDK',
    content: 'Max-Morrys a transforme ma vision du digital. Je suis passee de 0 a 5000 followers qualifies en 3 mois grace a ses conseils.',
    avatar: 'https://images.pexels.com/photos/3992656/pexels-photo-3992656.jpeg?auto=compress&cs=tinysrgb&w=200',
    rating: 5,
    featured: true,
  },
  {
    id: '4',
    name: 'Ibrahim Toure',
    role: 'Consultant SEO',
    content: 'La formation SEO est de loin la meilleure que j\'ai suivie. Le contenu est a jour et les techniques sont prouvees.',
    avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=200',
    rating: 4,
    featured: false,
  },
  {
    id: '5',
    name: 'Aissatou Ba',
    role: 'Community Manager',
    company: 'AgencePulse',
    content: 'Les podcasts sont une mine d\'or d\'informations. J\'ecoute chaque episode au moins deux fois.',
    avatar: 'https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?auto=compress&cs=tinysrgb&w=200',
    rating: 5,
    featured: false,
  },
];

export const faqs: FAQ[] = [
  { id: '1', question: 'Comment acceder aux formations apres l\'achat ?', answer: 'Apres votre achat, vous recevez un email avec vos identifiants. Connectez-vous a votre espace etudiant et accedez a vos cours immediatement. L\'acces est illimite.', category: 'Formations', order: 1 },
  { id: '2', question: 'Les formations sont-elles accessibles a vie ?', answer: 'Oui, une fois achetee, une formation est accessible a vie. Vous beneficiez egalement de toutes les mises a jour futures gratuitement.', category: 'Formations', order: 2 },
  { id: '3', question: 'Peut-on obtenir un certificat ?', answer: 'Oui, un certificat de completion est delivre a la fin de chaque formation. Il est telechargeable en PDF et partageable sur LinkedIn.', category: 'Formations', order: 3 },
  { id: '4', question: 'Quels sont les moyens de paiement acceptes ?', answer: 'Nous acceptons les paiements par Wave, Orange Money, carte bancaire et virement. D\'autres options sont en cours d\'integration.', category: 'Paiement', order: 4 },
  { id: '5', question: 'Existe-t-il une politique de remboursement ?', answer: 'Oui, vous disposez de 14 jours apres l\'achat pour demander un remboursement si la formation ne vous convient pas. Aucune question posee.', category: 'Paiement', order: 5 },
  { id: '6', question: 'Comment contacter le support ?', answer: 'Vous pouvez nous contacter via le formulaire de contact, par email ou directement via WhatsApp. Nous repondons en general sous 24h.', category: 'Support', order: 6 },
  { id: '7', question: 'Les contenus du blog sont-ils gratuits ?', answer: 'Oui, tous les articles, podcasts et videos publies sur la plateforme sont 100% gratuits et accessibles a tous.', category: 'Contenu', order: 7 },
  { id: '8', question: 'Comment rester informe des nouveaux contenus ?', answer: 'Inscrivez-vous a notre newsletter pour recevoir chaque semaine les derniers articles, episodes de podcast et annonces directement dans votre boite email.', category: 'Contenu', order: 8 },
];

export const announcements: Announcement[] = [
  {
    id: '1',
    title: 'Nouvelle formation IA disponible !',
    content: 'Decouvrez notre derniere formation sur l\'Intelligence Artificielle pour les entrepreneurs.',
    type: 'promo',
    active: true,
    startDate: '2026-02-01',
    endDate: '2026-03-31',
    link: '/formations/ia-pour-entrepreneurs',
  },
];

export const siteStats = {
  totalStudents: 1486,
  totalCourses: 5,
  completionRate: 98,
  trafficGrowth: '1790%+',
  revenue: 45000000,
};
